// Code generated by "stringer -type=SearchResult"; DO NOT EDIT.

package algorithms

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SearchResultUnknown-0]
	_ = x[SearchResultFound-1]
	_ = x[SearchResultGoLower-2]
	_ = x[SearchResultGoHigher-3]
}

const _SearchResult_name = "SearchResultUnknownSearchResultFoundSearchResultGoLowerSearchResultGoHigher"

var _SearchResult_index = [...]uint8{0, 19, 36, 55, 75}

func (i SearchResult) String() string {
	if i < 0 || i >= SearchResult(len(_SearchResult_index)-1) {
		return "SearchResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SearchResult_name[_SearchResult_index[i]:_SearchResult_index[i+1]]
}
